---
title: "Assignment 6"
author: "Kristina Koh"
date: "10/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
In this assignment, lead risk was determined by looking for households that had an income of less than $90000 and at least one child under the age of 6. 
Note: my summarize_all function does not work, so I used summarize and then kept the columns by writing x=x.

```{r,echo=FALSE, warning=FALSE, message=FALSE,include=FALSE}
library(censusapi)
library(tidyverse)
library(tigris)
library(sf)
library(leaflet)
library(dplyr)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

pums_2019_1yr <- getCensus(
  name = "acs/acs1/pums",
  vintage = 2019,
  region = "public use microdata area:*", 
  regionin = "state:06",
  vars = c(
    "SERIALNO",
    "SPORDER",
    "PWGTP",
    "WGTP",
    "AGEP",
    "SCHL",
    "PINCP",
    "RAC1P",
    "HISP",
    "LANX",
    "YBL",
    "HINCP",
    "BLD",
    "TEN",
    "PUMA",
    "MV"
  )
)

saveRDS(pums_2019_1yr, "a6_pums.rds")
pums_2019_1yr <- readRDS("a6_pums.rds")

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

sf_pums <- pums_2019_1yr %>% 
  mutate(
    PUMA = str_pad(public_use_microdata_area,5,"left","0")
  ) %>% 
  filter(PUMA %in% sf_pumas$PUMACE10)

sf_pums_clean <- sf_pums %>%
  mutate(
    YBL = as.numeric(YBL),
    AGEP = as.numeric(AGEP),
    HINCP = as.numeric(HINCP),
    MV = as.numeric(MV),
    BLD = as.numeric(BLD),
    TEN=as.numeric(TEN),
    PUMA = as.numeric(PUMA)
  ) %>% filter(YBL %in% 1:3) %>%
  mutate(leadrisk=ifelse(HINCP<90000 & AGEP %in% 0:6,1,0)) %>% group_by(SERIALNO,AGEP) %>% summarize(leadrisk=last(leadrisk),BLD=BLD,TEN=TEN,PUMA=PUMA,MV=MV)

logit_model <- glm(
  leadrisk ~ BLD+MV+TEN+PUMA,
  family = quasibinomial(),
  data = sf_pums_clean
)

summary(logit_model)

predict(logit_model, data.frame(PUMA = 07502, MV = 4, BLD = 5, TEN=6), type = "response")

```



```{r, echo=FALSE, warning=FALSE, message=FALSE}
logit_model <- glm(
  leadrisk ~ BLD+MV+TEN+PUMA,
  family = quasibinomial(),
  data = sf_pums_clean
)

summary(logit_model)

predict(logit_model, data.frame(PUMA = 07502, MV = 4, BLD = 5, TEN=6), type = "response")
```
The output above shows the response and its probability. 

