---
title: "KristinaKoh_A2"
output: html_document
---
Second update but still not done
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tigris)
library(sf)
library(censusapi)
library(dplyr)
library(mapview)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

smc_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:085",
    vars = "P1_001N"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P1_001N
  )


smc_pop_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block: *", 
    regionin = "state:06+county:085",
    vars = "P001001")%>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P001001

  )



library(devtools)
install_github('walkerke/tigris')
library(tigris)

smc_blocks_2020 <- blocks("CA", "Santa Clara", year = 2020, progress_bar = F)
sc_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "Cupertino")

smc_blocks_2010 <- blocks("CA", "Santa Clara", year = 2010, progress_bar = F)
sc_boundary_2010 <- places("CA", progress_bar = F) %>% 
  filter(NAME == "Cupertino")



bounds<-0
bounds <- (merge(smc_pop_2020,smc_pop_2010, by = "block",all=T))
bounds <- bounds%>%
  rename(pop2020=pop.x)
bounds <- bounds%>%
  rename(pop2010=pop.y)
perc_diff<-bounds %>% mutate(percentdiff= 100*(pop2020-pop2010)/((pop2010+pop2020)/2))
perc_diff<-na.omit(perc_diff)

map_perc_diff <- perc_diff %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[sc_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()

mapview(map_perc_diff, zcol = "percentdiff")
```
